import Head from "next/head";
import * as S from "./styles";

const CarouselItens = [
  { item: "/carouselItem1.png", price: "1,99" },
  { item: "/carouselItem2.png", price: "8,77" },
  { item: "/carouselItem3.png", price: "3,74" },
  { item: "/carouselItem4.png", price: "6,88" },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/home-icon.png" />
      </Head>
      <S.Body>
        <S.Header>
          <S.HeaderTitle>My products</S.HeaderTitle>
        </S.Header>
        <S.PageContainer>
          <S.Menu>
            <S.MenuTitle>Categories</S.MenuTitle>
            <S.MenuButon>- Healty & care</S.MenuButon>
            <S.MenuButon>- Food</S.MenuButon>
            <S.MenuButon>- Pet</S.MenuButon>
            <S.MenuButon>- Hardware</S.MenuButon>
            <S.MenuButon>- Flowers</S.MenuButon>
            <S.MenuButon>- Garden's</S.MenuButon>
            <S.MenuButon>- Beauty & Hair</S.MenuButon>
          </S.Menu>
          <S.AdvertasimentContainer>
            <S.MainAdvertisement>
              <S.MainAdvertisementImage
                src="/suplement.png"
                alt="Image of suplements"
              ></S.MainAdvertisementImage>
              <S.MainAdvertisementDescriptionContainer>
                <S.MainAdvertisementDescriptionPriceText>
                  $ 9,99
                </S.MainAdvertisementDescriptionPriceText>
                <S.MainAdvertisementDescription>
                  Super suplement for your health and well-being, natural and
                  100% functional, take advantage of this offer
                </S.MainAdvertisementDescription>
                <S.MainAdvertisementButton>Buy</S.MainAdvertisementButton>
              </S.MainAdvertisementDescriptionContainer>
            </S.MainAdvertisement>
            <S.ProductsCarousel>
              <S.CarouselButton>
                <img src="/leftButton.png" />
              </S.CarouselButton>
              {CarouselItens.map((item) => {
                return (
                  <S.carouselProductContainer>
                    <img src={item.item} />
                    <S.carouselProductPrice>
                      $ {item.price}
                    </S.carouselProductPrice>
                  </S.carouselProductContainer>
                );
              })}
              <S.CarouselButton>
                <img src="/rightButton.png" />
              </S.CarouselButton>
            </S.ProductsCarousel>
            <S.SubAdvertisement>
              <S.SubAdvertisementContainer>
                <S.SubAdvertisementItem>
                  <S.SubAdvertisementImage
                    src="/apple.png"
                    alt="Image of an apple"
                  />
                  <S.SubAdvertisementDescriptionContainer>
                    <S.SubAdvertisementDescriptionTitle>
                      Only $0.22
                    </S.SubAdvertisementDescriptionTitle>
                    <S.SubAdvertisementSmallDescription>
                      Healty power pills
                    </S.SubAdvertisementSmallDescription>
                    <S.SubAdvertisementSmallDescription>
                      Most Healthy for u
                    </S.SubAdvertisementSmallDescription>
                    <S.SubAdvertisementItalicDescription>
                      cheap and powerfull remedy for long term healing
                    </S.SubAdvertisementItalicDescription>
                  </S.SubAdvertisementDescriptionContainer>
                </S.SubAdvertisementItem>
                <S.SubAdvertisementButton>Buy now</S.SubAdvertisementButton>
              </S.SubAdvertisementContainer>
              <S.VerticalDivider />
              <S.SubAdvertisementContainer>
                <S.SubAdvertisementItem>
                  <S.SubAdvertisementImage
                    src="/water.png"
                    alt="Image of an apple"
                  />
                  <S.SubAdvertisementDescriptionContainer>
                    <S.SubAdvertisementDescriptionTitle>
                      Best drink
                    </S.SubAdvertisementDescriptionTitle>
                    <S.BorderedText>FOR FREE</S.BorderedText>
                    <S.SubAdvertisementMediumDescription>
                      Long term health
                    </S.SubAdvertisementMediumDescription>
                  </S.SubAdvertisementDescriptionContainer>
                </S.SubAdvertisementItem>
                <S.ClickAbleText href="https://www.wswork.com.br/">
                  Click here and join us with these magical benefits
                </S.ClickAbleText>
              </S.SubAdvertisementContainer>
            </S.SubAdvertisement>
          </S.AdvertasimentContainer>
          <S.FooterMessage>
            My customer - All rights not reserved - 2023
          </S.FooterMessage>
        </S.PageContainer>
      </S.Body>
    </>
  );
}
